// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC69dogGTn1muSSe0nx32Vm85ZnZzOTASk',
    appId: '1:745778684581:web:38d41500f1f1cd2d1f234c',
    messagingSenderId: '745778684581',
    projectId: 'hospital-system-5ae0e',
    authDomain: 'hospital-system-5ae0e.firebaseapp.com',
    storageBucket: 'hospital-system-5ae0e.firebasestorage.app',
    databaseURL: 'https://hospital-system-5ae0e-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCU6Sh07xscKGZ2C4uLArexhxPlBypI7U',
    appId: '1:745778684581:android:3b5ae0c2902a906a1f234c',
    messagingSenderId: '745778684581',
    projectId: 'hospital-system-5ae0e',
    storageBucket: 'hospital-system-5ae0e.firebasestorage.app',
    databaseURL: 'https://hospital-system-5ae0e-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC69dogGTn1muSSe0nx32Vm85ZnZzOTASk',
    appId: '1:745778684581:web:658da5ea8cfe83ae1f234c',
    messagingSenderId: '745778684581',
    projectId: 'hospital-system-5ae0e',
    authDomain: 'hospital-system-5ae0e.firebaseapp.com',
    storageBucket: 'hospital-system-5ae0e.firebasestorage.app',
    databaseURL: 'https://hospital-system-5ae0e-default-rtdb.firebaseio.com/'
  );
}
